[package]
name = "writing_to_reading_from_storage"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0", directory = "noir-projects/aztec-nr/aztec" }
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum" }                                                     # Using v0.6.0 as v0.6.1 has overflow issue in `to_field` fn.
