[package]
name = "empty_contract"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.76.4", directory = "noir-projects/aztec-nr/aztec" }
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum" }
