[package]
name = "bytes_storage_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v0.84.0", directory = "noir-projects/aztec-nr/aztec" }
