[package]
name = "transpiler_error"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.84.0", directory = "noir-projects/aztec-nr/aztec" }
